databases:
  - name: spendenapp-db
    region: frankfurt
    plan: free
    databaseName: spendenapp
    user: spendenapp

services:
  - type: web
    name: realcore-spendenapp
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: rm -rf node_modules .next && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: spendenapp-db
          property: connectionString
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_FROM
        sync: false
    healthCheckPath: /
    autoDeploy: true
